apiVersion: apps/v1
kind: Deployment
metadata:
  name: arun-ing-auth
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: c1
        image: arunvel1988/c1
        ports:
        - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: arun-svc
spec: 
  selector:
    app: web
  ports:
    - port: 8000
      name: http

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:  
  annotations:
    kubernetes.io/ingress.class: "nginx"    
    cert-manager.io/issuer: "letsencrypt-staging"
  name: arun-ingress
  namespace: default
spec:
  tls:
  - hosts:
    - app.info
    secretName: quickstart-example-tls
  rules:
  - host: app.info
    http:
      paths:
      - backend:
          serviceName: arun-svc
          servicePort: 8000
        path: /
 
    

